### ISSUE TITLE
Can you provide the data sets of train?

### ISSUE THREAD

**Issue by zhouxiaoshi** [harmanpreet93/nmt-with-rl#4]

**Comment by harmanpreet93** [comment]
Hey @zhouxiaoshi 

The `Pt-En` dataset was used from TensorFlow APIs and the `En-Fr` dataset was an internal dataset.

You can use the following code to load the `Pt-En` dataset.
```
import tensorflow_datasets as tfds
examples, metadata = tfds.load('ted_hrlr_translate/pt_to_en', with_info=True, as_supervised=True)
train_examples, val_examples = examples['train'], examples['validation']
```

**Comment by zhouxiaoshi** [comment]
Hey @Harmanpreet Singh
Due to I am in China,&nbsp; i can not link to that download link. Can i ask you to download the dataset and send it to me? If you can help me, i shall be very grateful.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "harmanpreet93/nmt-with-rl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月10日(星期四) 凌晨3:22
收件人:&nbsp;"harmanpreet93/nmt-with-rl"<nmt-with-rl@noreply.github.com&gt;;
抄送:&nbsp;"周小诗"<1171218105@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [harmanpreet93/nmt-with-rl] Can you provide the data sets of train? (#4)





 
Hey @zhouxiaoshi
 
The Pt-En dataset was used from TensorFlow APIs and the 'En-Fr` dataset was an internal dataset.
 
You can use the following code to load the Pt-En dataset.
 import tensorflow_datasets as tfds examples, metadata = tfds.load('ted_hrlr_translate/pt_to_en', with_info=True, as_supervised=True) train_examples, val_examples = examples['train'], examples['validation']

**Comment by zhouxiaoshi** [comment]
Hey @Harmanpreet Singh
Due to I am in China,&nbsp; i can not link to that download link. Can i ask you to download the dataset and send it to me? If you can help me, i shall be very grateful.


Hey @Harmanpreet Singh
I'm sorry to obtrude on you at such a time. The question has&nbsp;been resolved.&nbsp;&nbsp;Thank you!




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "harmanpreet93/nmt-with-rl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月10日(星期四) 凌晨3:22
收件人:&nbsp;"harmanpreet93/nmt-with-rl"<nmt-with-rl@noreply.github.com&gt;;
抄送:&nbsp;"周小诗"<1171218105@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [harmanpreet93/nmt-with-rl] Can you provide the data sets of train? (#4)





 
Hey @zhouxiaoshi
 
The Pt-En dataset was used from TensorFlow APIs and the 'En-Fr` dataset was an internal dataset.
 
You can use the following code to load the Pt-En dataset.
 import tensorflow_datasets as tfds examples, metadata = tfds.load('ted_hrlr_translate/pt_to_en', with_info=True, as_supervised=True) train_examples, val_examples = examples['train'], examples['validation']
