### ISSUE TITLE
When i run the train_model.sh, an error message says things like “No such file or directory:'./logs/log_pt_en/DL_50_Pos_epoch-26_prediction_en.txt'". 

### ISSUE THREAD

**Issue by zhouxiaoshi** [harmanpreet93/nmt-with-rl#5]
I found the code in train_model.py, but i can not understand what
"pred_file_path = "./logs/log_{}_{}/".format(inp_language, target_language) + checkpoint_path.split('/')[
        -1] + "_epoch-" + str(epoch) + "_prediction_{}.txt".format(target_language)" means?

**Comment by harmanpreet93** [comment]
This is just to set the prediction file path to save the translations for a small subset of examples while training.
